const translations = {
    en: {
        homeLink: "Home",
        aboutLink: "About Us",
        serviceLink: "Services",
        loginLink: "Login",
        registerLink: "Register",
        loginPageTitle: "Login - Jobsy",
        loginHeading: "Login",
        roleLabel: "Role",
        candidate: "Candidate",
        company: "Company",
        government: "Government",
        idLabel: "Email or Mobile",
        emailMobilePlaceholder: "Enter email or mobile",
        passwordLabel: "Password",
        passwordPlaceholder: "Enter password",
        loginBtn: "Login",
        noAccountText: "Don't have an account?",
        registerHereLink: "Register here",
        registerPageTitle: "Register - Jobsy",
        registerHeading: "Register",
        haveAccountText: "Already have an account?",
        loginHereLink: "Login here",
        nameLabel: "Full Name",
        namePlaceholder: "Enter your full name",
        professionalDetails: "Professional Details",
        resumeUploadLabel: "Upload Resume/CV (PDF only)",
        portfolioUrlLabel: "Portfolio/LinkedIn URL",
        educationalBackground: "Educational Background",
        educationLevelLabel: "Education Level",
        selectLevel: "Select Level",
        tenthPass: "10th Pass",
        twelfthPass: "12th Pass",
        diploma: "Diploma",
        graduate: "Graduate",
        postgraduate: "Postgraduate",
        universityLabel: "University/College",
        majorLabel: "Major/Field of Study",
        graduationYearLabel: "Year of Graduation",
        skillsAndInterests: "Skills and Interests",
        skillsInputLabel: "Your Skills (comma-separated)",
        workExperienceLabel: "Work Experience",
        addExperience: "Add New Experience",
        locationPreferenceLabel: "Location Preference",
        companyDetails: "Company Details",
        companyNameLabel: "Company Name",
        companySizeLabel: "Company Size",
        selectSize: "Select Size",
        size1: "1-10 employees",
        size2: "11-50 employees",
        size3: "51-200 employees",
        size4: "201-1000 employees",
        size5: "1000+ employees",
        industryLabel: "Industry",
        websiteUrlLabel: "Website URL",
        contactPersonLabel: "Contact Person",
        confirmPasswordLabel: "Confirm Password",
        registerBtn: "Register",
        heroBadge: "Verified Internships Platform",
        heroHeading: "Find Safe Internships. Build Real Skills.",
        heroText: "Stop worrying about fake postings. We verify every internship, track your skill gaps, and help you grow with personalized roadmaps.",
        getStartedBtn: "Get Started",
        learnMoreBtn: "Learn More",
        verifiedInternships: "Verified Internships",
        trustScore: "Trust Score",
        aiSupport: "AI Support",
        aboutHeading: "About Us",
        aboutText: "We're building a safer way for students to find internships. Too many fake postings and scams out there - we're fixing that.",
        whoWeAre: "Who We Are",
        whoWeAreText: "A team of developers who got tired of seeing students fall for internship scams. We built this platform to verify opportunities, track fraud, and help students actually grow their skills.",
        theProblem: "The Problem",
        theProblemText: "Students waste time on fake internships. Companies post unclear requirements. No one's monitoring what's real and what's not. Career paths feel confusing without proper guidance.",
        whatWeDo: "What We Do",
        whatWeDoText: "We verify internships before they reach you. Each posting gets a trust score. Government bodies can monitor fraud patterns. Students get skill roadmaps based on what companies actually need. Simple as that.",
        whatMakesUsDifferent: "What Makes Us Different",
        trustScoring: "Trust Scoring",
        trustScoringText: "Every internship gets checked. Company history, reviews, red flags - we score it all so you know what's legit.",
        skillRoadmaps: "Skill Roadmaps",
        skillRoadmapsText: "We analyze what skills you have and what jobs need. Then build you a learning path that actually makes sense.",
        fraudMonitoring: "Fraud Monitoring",
        fraudMonitoringText: "Government dashboards track scam patterns. Students can report suspicious postings. We keep the platform clean.",
        servicesHeading: "Services",
        servicesText: "Here's what we offer to keep your internship search safe and effective.",
        internshipVerification: "Internship Verification",
        internshipVerificationText: "AI checks company details, past reviews, and scam signals. Shows trust rating - High, Medium, or Low.",
        scamDetection: "Scam Detection",
        scamDetectionText: "Alerts for fraud patterns, duplicate postings, and suspicious payment requests. We flag it before you apply.",
        governmentDashboard: "Government Dashboard",
        governmentDashboardText: "Real-time analytics for monitoring bodies. Track fraud complaints, verify companies, see regional scam data.",
        skillGapAnalysis: "Skill Gap Analysis",
        skillGapAnalysisText: "Compare your skills with job requirements. See exactly what you're missing for your target role.",
        learningRoadmaps: "Learning Roadmaps",
        learningRoadmapsText: "Personalized plans from beginner to advanced. Weekly goals, course recommendations, clear progression.",
        skillAssessments: "Skill Assessments",
        skillAssessmentsText: "Take quizzes in your domain. Get scored, see where you stand, get improvement suggestions.",
        verifiedListings: "Verified Listings",
        verifiedListingsText: "Only approved internships show up. Government and college-verified opportunities you can trust.",
        reportSystem: "Report System",
        reportSystemText: "Found something fishy? Report it. We track complaints and take action on fraudulent postings.",
        getInTouch: "Get in Touch",
        getInTouchText: "Questions? Issues? Just want to talk? Drop us a message.",
        emailUs: "Email Us",
        footerText: "© 2026 Jobsy — By Team TechTara.",
        welcomeBack: "Welcome back",
        dashboard: "Dashboard",
        browseInternships: "Browse Internships",
        myApplications: "My Applications",
        saved: "Saved",
        skillGap: "Skill Gap Analysis",
        learningRoadmap: "Learning Roadmap",
        takeQuiz: "Take Quiz",
        profile: "Profile",
        aiAssistant: "AI Assistant",
        logout: "Logout",
        applications: "Applications",
        interviews: "Interviews",
        profileViews: "Profile Views",
        recentApplications: "Recent Applications",
        recommendedForYou: "Recommended for You",
        welcome: "Welcome",
        activePostings: "Active Postings",
        totalApplications: "Total Applications",
        shortlisted: "Shortlisted",
        hired: "Hired",
        myPostings: "My Postings",
        candidates: "Candidates",
        analytics: "Analytics",
        companyProfile: "Company Profile",
        postInternship: "Post Internship",
        governmentMonitoring: "Government Monitoring Dashboard",
        totalCompanies: "Total Companies",
        fraudReports: "Fraud Reports",
        verifiedCompanies: "Verified Companies",
        actionsTaken: "Actions Taken",
        recentFraudReports: "Recent Fraud Reports",
        pendingVerifications: "Pending Verifications",
        companies: "Companies",
        verificationQueue: "Verification Queue",
        regionalData: "Regional Data",
        addToResume: "Add to Resume",
        clickToCopy: "Click to copy",
        keywordCopied: "copied!",
        scanningInternships: "Scanning for internships...",
        noInternshipsAvailable: "No internships available at the moment.",
        applyNow: "Apply Now",
        save: "Save"
    },
    hi: {
        homeLink: "होम",
        aboutLink: "हमारे बारे में",
        serviceLink: "सेवाएं",
        loginLink: "लॉगिन",
        registerLink: "रजिस्टर",
        loginPageTitle: "लॉगिन - Jobsy",
        loginHeading: "लॉगिन",
        roleLabel: "भूमिका",
        candidate: "उम्मीदवार",
        company: "कंपनी",
        government: "सरकार",
        idLabel: "ईमेल या मोबाइल",
        emailMobilePlaceholder: "ईमेल या मोबाइल दर्ज करें",
        passwordLabel: "पासवर्ड",
        passwordPlaceholder: "पासवर्ड दर्ज करें",
        loginBtn: "लॉगिन",
        noAccountText: "खाता नहीं है?",
        registerHereLink: "यहां रजिस्टर करें",
        registerPageTitle: "रजिस्टर - Jobsy",
        registerHeading: "रजिस्टर",
        haveAccountText: "पहले से खाता है?",
        loginHereLink: "यहां लॉगिन करें",
        nameLabel: "पूरा नाम",
        namePlaceholder: "अपना पूरा नाम दर्ज करें",
        professionalDetails: "पेशेवर विवरण",
        resumeUploadLabel: "रिज्यूमे/सीवी अपलोड करें (केवल पीडीएफ)",
        portfolioUrlLabel: "पोर्टफोलियो/लिंक्डइन यूआरएल",
        educationalBackground: "शैक्षणिक पृष्ठभूमि",
        educationLevelLabel: "शिक्षा का स्तर",
        selectLevel: "स्तर चुनें",
        tenthPass: "10वीं पास",
        twelfthPass: "12वीं पास",
        diploma: "डिप्लोमा",
        graduate: "स्नातक",
        postgraduate: "स्नातकोत्तर",
        universityLabel: "विश्वविद्यालय/कॉलेज",
        majorLabel: "प्रमुख/अध्ययन क्षेत्र",
        graduationYearLabel: "स्नातक वर्ष",
        skillsAndInterests: "कौशल और रुचियां",
        skillsInputLabel: "आपके कौशल (कॉमा से अलग)",
        workExperienceLabel: "कार्य अनुभव",
        addExperience: "नया अनुभव जोड़ें",
        locationPreferenceLabel: "स्थान प्राथमिकता",
        companyDetails: "कंपनी विवरण",
        companyNameLabel: "कंपनी का नाम",
        companySizeLabel: "कंपनी का आकार",
        selectSize: "आकार चुनें",
        size1: "1-10 कर्मचारी",
        size2: "11-50 कर्मचारी",
        size3: "51-200 कर्मचारी",
        size4: "201-1000 कर्मचारी",
        size5: "1000+ कर्मचारी",
        industryLabel: "उद्योग",
        websiteUrlLabel: "वेबसाइट यूआरएल",
        contactPersonLabel: "संपर्क व्यक्ति",
        confirmPasswordLabel: "पासवर्ड की पुष्टि करें",
        registerBtn: "रजिस्टर",
        heroBadge: "सत्यापित इंटर्नशिप प्लेटफॉर्म",
        heroHeading: "सुरक्षित इंटर्नशिप खोजें। वास्तविक कौशल बनाएं।",
        heroText: "नकली पोस्टिंग की चिंता करना बंद करें। हम हर इंटर्नशिप को सत्यापित करते हैं, आपके कौशल अंतराल को ट्रैक करते हैं, और व्यक्तिगत रोडमैप के साथ आपको बढ़ने में मदद करते हैं।",
        getStartedBtn: "शुरू करें",
        learnMoreBtn: "और जानें",
        verifiedInternships: "सत्यापित इंटर्नशिप",
        trustScore: "विश्वास स्कोर",
        aiSupport: "AI सहायता",
        aboutHeading: "हमारे बारे में",
        aboutText: "हम छात्रों के लिए इंटर्नशिप खोजने का एक सुरक्षित तरीका बना रहे हैं। बहुत सारी नकली पोस्टिंग और घोटाले हैं - हम इसे ठीक कर रहे हैं।",
        whoWeAre: "हम कौन हैं",
        whoWeAreText: "डेवलपर्स की एक टीम जो छात्रों को इंटर्नशिप घोटालों में फंसते देखकर थक गई। हमने अवसरों को सत्यापित करने, धोखाधड़ी को ट्रैक करने और छात्रों को वास्तव में अपने कौशल बढ़ाने में मदद करने के लिए यह प्लेटफॉर्म बनाया।",
        theProblem: "समस्या",
        theProblemText: "छात्र नकली इंटर्नशिप पर समय बर्बाद करते हैं। कंपनियां अस्पष्ट आवश्यकताएं पोस्ट करती हैं। कोई भी निगरानी नहीं कर रहा है कि क्या वास्तविक है और क्या नहीं। उचित मार्गदर्शन के बिना करियर पथ भ्रमित करने वाले लगते हैं।",
        whatWeDo: "हम क्या करते हैं",
        whatWeDoText: "हम इंटर्नशिप को आप तक पहुंचने से पहले सत्यापित करते हैं। प्रत्येक पोस्टिंग को एक विश्वास स्कोर मिलता है। सरकारी निकाय धोखाधड़ी के पैटर्न की निगरानी कर सकते हैं। छात्रों को कंपनियों की वास्तविक जरूरतों के आधार पर कौशल रोडमैप मिलते हैं।",
        whatMakesUsDifferent: "हमें क्या अलग बनाता है",
        trustScoring: "विश्वास स्कोरिंग",
        trustScoringText: "हर इंटर्नशिप की जांच की जाती है। कंपनी का इतिहास, समीक्षाएं, लाल झंडे - हम सब कुछ स्कोर करते हैं ताकि आप जान सकें कि क्या वैध है।",
        skillRoadmaps: "कौशल रोडमैप",
        skillRoadmapsText: "हम विश्लेषण करते हैं कि आपके पास कौन से कौशल हैं और नौकरियों को क्या चाहिए। फिर आपके लिए एक सीखने का रास्ता बनाते हैं जो वास्तव में समझ में आता है।",
        fraudMonitoring: "धोखाधड़ी निगरानी",
        fraudMonitoringText: "सरकारी डैशबोर्ड घोटाले के पैटर्न को ट्रैक करते हैं। छात्र संदिग्ध पोस्टिंग की रिपोर्ट कर सकते हैं। हम प्लेटफॉर्म को साफ रखते हैं।",
        servicesHeading: "सेवाएं",
        servicesText: "आपकी इंटर्नशिप खोज को सुरक्षित और प्रभावी रखने के लिए हम यह पेश करते हैं।",
        internshipVerification: "इंटर्नशिप सत्यापन",
        internshipVerificationText: "AI कंपनी विवरण, पिछली समीक्षाओं और घोटाले के संकेतों की जांच करता है। विश्वास रेटिंग दिखाता है - उच्च, मध्यम या निम्न।",
        scamDetection: "घोटाला पहचान",
        scamDetectionText: "धोखाधड़ी पैटर्न, डुप्लिकेट पोस्टिंग और संदिग्ध भुगतान अनुरोधों के लिए अलर्ट। हम आपके आवेदन करने से पहले इसे फ्लैग करते हैं।",
        governmentDashboard: "सरकारी डैशबोर्ड",
        governmentDashboardText: "निगरानी निकायों के लिए रीयल-टाइम एनालिटिक्स। धोखाधड़ी की शिकायतों को ट्रैक करें, कंपनियों को सत्यापित करें, क्षेत्रीय घोटाले डेटा देखें।",
        skillGapAnalysis: "कौशल अंतराल विश्लेषण",
        skillGapAnalysisText: "अपने कौशल की नौकरी की आवश्यकताओं से तुलना करें। अपनी लक्षित भूमिका के लिए आपको क्या कमी है, वह देखें।",
        learningRoadmaps: "सीखने के रोडमैप",
        learningRoadmapsText: "शुरुआती से उन्नत तक व्यक्तिगत योजनाएं। साप्ताहिक लक्ष्य, पाठ्यक्रम सिफारिशें, स्पष्ट प्रगति।",
        skillAssessments: "कौशल मूल्यांकन",
        skillAssessmentsText: "अपने डोमेन में क्विज़ लें। स्कोर प्राप्त करें, देखें कि आप कहां खड़े हैं, सुधार सुझाव प्राप्त करें।",
        verifiedListings: "सत्यापित सूचियां",
        verifiedListingsText: "केवल अनुमोदित इंटर्नशिप दिखाई देती हैं। सरकार और कॉलेज-सत्यापित अवसर जिन पर आप भरोसा कर सकते हैं।",
        reportSystem: "रिपोर्ट सिस्टम",
        reportSystemText: "कुछ संदिग्ध पाया? इसकी रिपोर्ट करें। हम शिकायतों को ट्रैक करते हैं और धोखाधड़ी वाली पोस्टिंग पर कार्रवाई करते हैं।",
        getInTouch: "संपर्क में रहें",
        getInTouchText: "प्रश्न? समस्याएं? बस बात करना चाहते हैं? हमें एक संदेश भेजें।",
        emailUs: "हमें ईमेल करें",
        footerText: "© 2026 Jobsy — टीम TechTara द्वारा।",
        welcomeBack: "वापस स्वागत है",
        dashboard: "डैशबोर्ड",
        browseInternships: "इंटर्नशिप ब्राउज़ करें",
        myApplications: "मेरे आवेदन",
        saved: "सहेजे गए",
        skillGap: "कौशल अंतराल विश्लेषण",
        learningRoadmap: "सीखने का रोडमैप",
        takeQuiz: "क्विज़ लें",
        profile: "प्रोफ़ाइल",
        aiAssistant: "AI सहायक",
        logout: "लॉगआउट",
        applications: "आवेदन",
        interviews: "साक्षात्कार",
        profileViews: "प्रोफ़ाइल दृश्य",
        recentApplications: "हाल के आवेदन",
        recommendedForYou: "आपके लिए अनुशंसित",
        welcome: "स्वागत है",
        activePostings: "सक्रिय पोस्टिंग",
        totalApplications: "कुल आवेदन",
        shortlisted: "शॉर्टलिस्ट किए गए",
        hired: "नियुक्त",
        myPostings: "मेरी पोस्टिंग",
        candidates: "उम्मीदवार",
        analytics: "विश्लेषण",
        companyProfile: "कंपनी प्रोफ़ाइल",
        postInternship: "इंटर्नशिप पोस्ट करें",
        governmentMonitoring: "सरकारी निगरानी डैशबोर्ड",
        totalCompanies: "कुल कंपनियां",
        fraudReports: "धोखाधड़ी रिपोर्ट",
        verifiedCompanies: "सत्यापित कंपनियां",
        actionsTaken: "की गई कार्रवाई",
        recentFraudReports: "हाल की धोखाधड़ी रिपोर्ट",
        pendingVerifications: "लंबित सत्यापन",
        companies: "कंपनियां",
        verificationQueue: "सत्यापन कतार",
        regionalData: "क्षेत्रीय डेटा",
        addToResume: "रिज्यूमे में जोड़ें",
        clickToCopy: "कॉपी करने के लिए क्लिक करें",
        keywordCopied: "कॉपी किया गया!",
        scanningInternships: "इंटर्नशिप स्कैन कर रहे हैं...",
        noInternshipsAvailable: "इस समय कोई इंटर्नशिप उपलब्ध नहीं है।",
        applyNow: "अभी आवेदन करें",
        save: "सहेजें"
    },
    mr: {
        homeLink: "मुख्यपृष्ठ",
        aboutLink: "आमच्याबद्दल",
        serviceLink: "सेवा",
        loginLink: "लॉगिन",
        registerLink: "नोंदणी",
        loginPageTitle: "लॉगिन - Jobsy",
        loginHeading: "लॉगिन",
        roleLabel: "भूमिका",
        candidate: "उमेदवार",
        company: "कंपनी",
        government: "सरकार",
        idLabel: "ईमेल किंवा मोबाइल",
        emailMobilePlaceholder: "ईमेल किंवा मोबाइल प्रविष्ट करा",
        passwordLabel: "पासवर्ड",
        passwordPlaceholder: "पासवर्ड प्रविष्ट करा",
        loginBtn: "लॉगिन",
        noAccountText: "खाते नाही?",
        registerHereLink: "येथे नोंदणी करा",
        registerPageTitle: "नोंदणी - Jobsy",
        registerHeading: "नोंदणी",
        haveAccountText: "आधीच खाते आहे?",
        loginHereLink: "येथे लॉगिन करा",
        nameLabel: "पूर्ण नाव",
        namePlaceholder: "तुमचे पूर्ण नाव प्रविष्ट करा",
        professionalDetails: "व्यावसायिक तपशील",
        resumeUploadLabel: "रेझ्युमे/सीव्ही अपलोड करा (केवळ पीडीएफ)",
        portfolioUrlLabel: "पोर्टफोलिओ/लिंक्डइन यूआरएल",
        educationalBackground: "शैक्षणिक पार्श्वभूमी",
        educationLevelLabel: "शिक्षण स्तर",
        selectLevel: "स्तर निवडा",
        tenthPass: "10वी उत्तीर्ण",
        twelfthPass: "12वी उत्तीर्ण",
        diploma: "डिप्लोमा",
        graduate: "पदवीधर",
        postgraduate: "पदव्युत्तर",
        universityLabel: "विद्यापीठ/महाविद्यालय",
        majorLabel: "प्रमुख/अभ्यास क्षेत्र",
        graduationYearLabel: "पदवीचे वर्ष",
        skillsAndInterests: "कौशल्ये आणि आवडी",
        skillsInputLabel: "तुमची कौशल्ये (कॉमाने वेगळे)",
        workExperienceLabel: "कामाचा अनुभव",
        addExperience: "नवीन अनुभव जोडा",
        locationPreferenceLabel: "ठिकाण प्राधान्य",
        companyDetails: "कंपनी तपशील",
        companyNameLabel: "कंपनीचे नाव",
        companySizeLabel: "कंपनीचा आकार",
        selectSize: "आकार निवडा",
        size1: "1-10 कर्मचारी",
        size2: "11-50 कर्मचारी",
        size3: "51-200 कर्मचारी",
        size4: "201-1000 कर्मचारी",
        size5: "1000+ कर्मचारी",
        industryLabel: "उद्योग",
        websiteUrlLabel: "वेबसाइट यूआरएल",
        contactPersonLabel: "संपर्क व्यक्ती",
        confirmPasswordLabel: "पासवर्डची पुष्टी करा",
        registerBtn: "नोंदणी",
        heroBadge: "सत्यापित इंटर्नशिप प्लॅटफॉर्म",
        heroHeading: "सुरक्षित इंटर्नशिप शोधा. खरी कौशल्ये तयार करा.",
        heroText: "बनावट पोस्टिंगची काळजी करणे थांबवा. आम्ही प्रत्येक इंटर्नशिपची पडताळणी करतो, तुमच्या कौशल्य अंतराचा मागोवा घेतो आणि वैयक्तिकृत रोडमॅपसह तुम्हाला वाढण्यास मदत करतो.",
        getStartedBtn: "सुरू करा",
        learnMoreBtn: "अधिक जाणून घ्या",
        verifiedInternships: "सत्यापित इंटर्नशिप",
        trustScore: "विश्वास स्कोअर",
        aiSupport: "AI समर्थन",
        aboutHeading: "आमच्याबद्दल",
        aboutText: "आम्ही विद्यार्थ्यांसाठी इंटर्नशिप शोधण्याचा एक सुरक्षित मार्ग तयार करत आहोत. खूप बनावट पोस्टिंग आणि घोटाळे आहेत - आम्ही ते दुरुस्त करत आहोत.",
        whoWeAre: "आम्ही कोण आहोत",
        whoWeAreText: "डेव्हलपर्सची एक टीम जी विद्यार्थ्यांना इंटर्नशिप घोटाळ्यांमध्ये अडकताना पाहून थकली. आम्ही संधींची पडताळणी करण्यासाठी, फसवणूक ट्रॅक करण्यासाठी आणि विद्यार्थ्यांना त्यांची कौशल्ये वाढविण्यात मदत करण्यासाठी हे प्लॅटफॉर्म तयार केले.",
        theProblem: "समस्या",
        theProblemText: "विद्यार्थी बनावट इंटर्नशिपवर वेळ वाया घालवतात. कंपन्या अस्पष्ट आवश्यकता पोस्ट करतात. काय खरे आहे आणि काय नाही याचे कोणी निरीक्षण करत नाही. योग्य मार्गदर्शनाशिवाय करिअर मार्ग गोंधळात टाकणारे वाटतात.",
        whatWeDo: "आम्ही काय करतो",
        whatWeDoText: "आम्ही इंटर्नशिप तुमच्यापर्यंत पोहोचण्यापूर्वी त्यांची पडताळणी करतो. प्रत्येक पोस्टिंगला विश्वास स्कोअर मिळतो. सरकारी संस्था फसवणुकीच्या पॅटर्नचे निरीक्षण करू शकतात. विद्यार्थ्यांना कंपन्यांना खरोखर काय हवे आहे त्यावर आधारित कौशल्य रोडमॅप मिळतात.",
        whatMakesUsDifferent: "आम्हाला काय वेगळे बनवते",
        trustScoring: "विश्वास स्कोअरिंग",
        trustScoringText: "प्रत्येक इंटर्नशिपची तपासणी केली जाते. कंपनीचा इतिहास, पुनरावलोकने, लाल झेंडे - आम्ही सर्व काही स्कोअर करतो जेणेकरून तुम्हाला काय कायदेशीर आहे हे कळेल.",
        skillRoadmaps: "कौशल्य रोडमॅप",
        skillRoadmapsText: "तुमच्याकडे कोणती कौशल्ये आहेत आणि नोकऱ्यांना काय हवे आहे याचे आम्ही विश्लेषण करतो. मग तुमच्यासाठी एक शिकण्याचा मार्ग तयार करतो जो खरोखर अर्थपूर्ण आहे.",
        fraudMonitoring: "फसवणूक निरीक्षण",
        fraudMonitoringText: "सरकारी डॅशबोर्ड घोटाळ्याच्या पॅटर्नचा मागोवा घेतात. विद्यार्थी संशयास्पद पोस्टिंगची तक्रार करू शकतात. आम्ही प्लॅटफॉर्म स्वच्छ ठेवतो.",
        servicesHeading: "सेवा",
        servicesText: "तुमचा इंटर्नशिप शोध सुरक्षित आणि प्रभावी ठेवण्यासाठी आम्ही हे ऑफर करतो.",
        internshipVerification: "इंटर्नशिप पडताळणी",
        internshipVerificationText: "AI कंपनी तपशील, मागील पुनरावलोकने आणि घोटाळ्याच्या संकेतांची तपासणी करते. विश्वास रेटिंग दाखवते - उच्च, मध्यम किंवा कमी.",
        scamDetection: "घोटाळा शोध",
        scamDetectionText: "फसवणूक पॅटर्न, डुप्लिकेट पोस्टिंग आणि संशयास्पद पेमेंट विनंत्यांसाठी अलर्ट. तुम्ही अर्ज करण्यापूर्वी आम्ही ते फ्लॅग करतो.",
        governmentDashboard: "सरकारी डॅशबोर्ड",
        governmentDashboardText: "निरीक्षण संस्थांसाठी रिअल-टाइम अॅनालिटिक्स. फसवणुकीच्या तक्रारींचा मागोवा घ्या, कंपन्यांची पडताळणी करा, प्रादेशिक घोटाळा डेटा पहा.",
        skillGapAnalysis: "कौशल्य अंतर विश्लेषण",
        skillGapAnalysisText: "तुमच्या कौशल्यांची नोकरीच्या आवश्यकतांशी तुलना करा. तुमच्या लक्ष्य भूमिकेसाठी तुम्हाला नेमके काय कमी आहे ते पहा.",
        learningRoadmaps: "शिकण्याचे रोडमॅप",
        learningRoadmapsText: "सुरुवातीपासून प्रगत पर्यंत वैयक्तिकृत योजना. साप्ताहिक उद्दिष्टे, अभ्यासक्रम शिफारसी, स्पष्ट प्रगती.",
        skillAssessments: "कौशल्य मूल्यांकन",
        skillAssessmentsText: "तुमच्या डोमेनमध्ये क्विझ घ्या. स्कोअर मिळवा, तुम्ही कुठे उभे आहात ते पहा, सुधारणा सूचना मिळवा.",
        verifiedListings: "सत्यापित सूची",
        verifiedListingsText: "फक्त मंजूर इंटर्नशिप दिसतात. सरकार आणि कॉलेज-सत्यापित संधी ज्यावर तुम्ही विश्वास ठेवू शकता.",
        reportSystem: "अहवाल प्रणाली",
        reportSystemText: "काहीतरी संशयास्पद आढळले? त्याची तक्रार करा. आम्ही तक्रारींचा मागोवा घेतो आणि फसव्या पोस्टिंगवर कारवाई करतो.",
        getInTouch: "संपर्कात रहा",
        getInTouchText: "प्रश्न? समस्या? फक्त बोलायचे आहे? आम्हाला संदेश पाठवा.",
        emailUs: "आम्हाला ईमेल करा",
        footerText: "© 2026 Jobsy — टीम TechTara द्वारे.",
        welcomeBack: "परत स्वागत आहे",
        dashboard: "डॅशबोर्ड",
        browseInternships: "इंटर्नशिप ब्राउझ करा",
        myApplications: "माझे अर्ज",
        saved: "जतन केलेले",
        skillGap: "कौशल्य अंतर विश्लेषण",
        learningRoadmap: "शिकण्याचा रोडमॅप",
        takeQuiz: "क्विझ घ्या",
        profile: "प्रोफाइल",
        aiAssistant: "AI सहाय्यक",
        logout: "लॉगआउट",
        applications: "अर्ज",
        interviews: "मुलाखती",
        profileViews: "प्रोफाइल दृश्ये",
        recentApplications: "अलीकडील अर्ज",
        recommendedForYou: "तुमच्यासाठी शिफारस केलेले",
        welcome: "स्वागत आहे",
        activePostings: "सक्रिय पोस्टिंग",
        totalApplications: "एकूण अर्ज",
        shortlisted: "शॉर्टलिस्ट केलेले",
        hired: "नियुक्त",
        myPostings: "माझी पोस्टिंग",
        candidates: "उमेदवार",
        analytics: "विश्लेषण",
        companyProfile: "कंपनी प्रोफाइल",
        postInternship: "इंटर्नशिप पोस्ट करा",
        governmentMonitoring: "सरकारी निरीक्षण डॅशबोर्ड",
        totalCompanies: "एकूण कंपन्या",
        fraudReports: "फसवणूक अहवाल",
        verifiedCompanies: "सत्यापित कंपन्या",
        actionsTaken: "केलेल्या कारवाया",
        recentFraudReports: "अलीकडील फसवणूक अहवाल",
        pendingVerifications: "प्रलंबित सत्यापन",
        companies: "कंपन्या",
        verificationQueue: "सत्यापन रांग",
        regionalData: "प्रादेशिक डेटा",
        addToResume: "रेझ्युमेमध्ये जोडा",
        clickToCopy: "कॉपी करण्यासाठी क्लिक करा",
        keywordCopied: "कॉपी केले!",
        scanningInternships: "इंटर्नशिप स्कॅन करत आहे...",
        noInternshipsAvailable: "या वेळी कोणतीही इंटर्नशिप उपलब्ध नाही.",
        applyNow: "आता अर्ज करा",
        save: "जतन करा"
    }
};

function updateLanguage(lang) {
    document.querySelectorAll("[data-i18n]").forEach(el => {
        const key = el.getAttribute("data-i18n");
        const translation = translations[lang] ? translations[lang][key] : null;
        if (translation) {
            el.textContent = translation;
        }
    });
}

function showNotification(message, type = 'info') {
    const notification = document.createElement('div');
    const colors = {
        success: '#10b981',
        error: '#ef4444',
        warning: '#f59e0b',
        info: '#3b82f6'
    };
    notification.textContent = message;
    notification.style.cssText = `position:fixed;top:20px;right:20px;background:${colors[type]};color:#fff;padding:12px 20px;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,0.1);z-index:10000;animation:slideIn 0.3s ease;max-width:300px;word-wrap:break-word;`;
    document.body.appendChild(notification);
    setTimeout(() => {
        notification.style.animation = 'slideOut 0.3s ease';
        setTimeout(() => notification.remove(), 300);
    }, 3000);
}

window.alert = function(message) {
    showNotification(message, 'info');
};

window.showSuccess = function(message) {
    showNotification(message, 'success');
};

window.showError = function(message) {
    showNotification(message, 'error');
};

window.showWarning = function(message) {
    showNotification(message, 'warning');
};

document.addEventListener("DOMContentLoaded", () => {
    const langSelect = document.getElementById("language");
    const currentLang = localStorage.getItem('appLang') || 'en';
    if (langSelect) {
        langSelect.value = currentLang;
    }
    updateLanguage(currentLang);
    if (langSelect) {
        langSelect.addEventListener("change", (event) => {
            const selectedLang = event.target.value;
            localStorage.setItem('appLang', selectedLang);
            updateLanguage(selectedLang);
        });
    }
    document.getElementById('mainOverlay')?.addEventListener('click', () => {
        document.querySelector('nav').classList.remove('active');
        document.getElementById('mainOverlay').classList.remove('active');
    });
});
